title: Attila Klenik
logo: /assets/img/klenik.png
description: Computer scientist, PhD
website1: https://ftsrg.mit.bme.hu/hu/
affiliation1: ftsrg
title1: Software Engineer
scholar: l9E8dTQAAAAJ
mail: attila.klenik@vik.bme.hu
linkedin: attila-klenik
cv: https://aklenik.github.io/klenik-cv-en.pdf
mtmt: https://m2.mtmt.hu/gui2/?type=authors&mode=browse&sel=10056599
twitter: a_klenik
theme: jekyll-theme-minimal